name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Revisar el repositorio Git
        uses: actions/checkout@v3

      - name: Instalar y preparar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar y preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Instalar dependencias
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash